# vim:fileencoding=utf-8:foldmethod=marker

# Font {{{
font_family      family='IBM Plex Mono' postscript_name=IBMPlexMono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
# }}}

# Cursor {{{
# cursor #cccccc
# cursor_text_color #111111
cursor_shape block
shell_integration no-cursor
cursor_shape_unfocused hollow
cursor_blink_interval -0.5
cursor_stop_blinking_after 15.0
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 3
cursor_trail_color none
# }}}

# Scrollback {{{
scrollback_lines 6000
scrollbar never
# }}}

# Mouse {{{
url_color #0087bd
url_style curly
open_url_with default
underline_hyperlinks always
strip_trailing_spaces smart
# }}}

# Performance tuning {{{
repaint_delay 10
sync_to_monitor yes
# }}}

# Window {{{
remember_window_size  yes
initial_window_width  640
initial_window_height 400
remember_window_position no
draw_minimal_borders no
confirm_os_window_close 0
# }}}

# Tab Bar {{{
tab_bar_edge top
tab_bar_style powerline
# }}}

# Color scheme {{{
foreground #dddddd
background #000000
background_opacity 0.7
# }}}

# The color table {{{

#: black
# color0 #000000
# color8 #767676

#: red
# color1 #cc0403
# color9 #f2201f

#: green
# color2  #19cb00
# color10 #23fd00

#: yellow
# color3  #cecb00
# color11 #fffd00

#: blue
# color4  #0d73cc
# color12 #1a8fff

#: magenta
# color5  #cb1ed1
# color13 #fd28ff

#: cyan
# color6  #0dcdcd
# color14 #14ffff

# white
# color7  #dddddd
# color15 #ffffff

# }}}

#: Window management {{{
# New window
map kitty_mod+enter new_window

#: Close window
map kitty_mod+w close_window

#: Next window
map kitty_mod+] next_window

#: Previous window
map kitty_mod+[ previous_window

#: Move window forward
map kitty_mod+f move_window_forward

#: Move window backward
map kitty_mod+b move_window_backward

#: Move window to top
map kitty_mod+` move_window_to_top

#: Start resizing window
map kitty_mod+r start_resizing_window

#: Visually select and focus window
map kitty_mod+f7 focus_visible_window

#: Visually swap window with another
map kitty_mod+f8 swap_with_window

#: }}}

#: Tab management {{{
#: Next tab
map ctrl+tab        next_tab

#: Previous tab
map ctrl+shift+tab previous_tab

#: New tab
map kitty_mod+t new_tab

#: Close tab
map kitty_mod+q close_tab

#: Move tab forward
map kitty_mod+. move_tab_forward

#: Move tab backward
map kitty_mod+, move_tab_backward

#: Set tab title
map kitty_mod+alt+t set_tab_title
#: }}}

#: Layout management {{{
#: Next layout
map kitty_mod+l next_layout
#: }}}

#: Font sizes {{{
#: Increase font size
map kitty_mod+plus   change_font_size all +2.0

#: Decrease font size
map kitty_mod+minus       change_font_size all -2.0

#: Reset font size
map kitty_mod+backspace change_font_size all 0
#: }}}

#: Miscellaneous {{{
#: Reload kitty.conf
map kitty_mod+f5 load_config_file
#: }}}
