### Directories and Files ###
music_directory		    "~/Music"
playlist_directory		"~/.mpd/playlists"
db_file			        "~/.mpd/database"
pid_file			    "~/.mpd/pid"
state_file			    "~/.mpd/state"
sticker_file			"~/.mpd/sticker.sql"

### General music daemon options ###
bind_to_address	        "localhost"
port                    "6600"
restore_paused          "yes"
auto_update	            "yes"

### Audio Output ###
audio_output {
	type                 "alsa"
	name                "My ALSA Device"
	mixer_control       "PCM"		
}

audio_output {
	type                "fifo"
	name                "my_fifo"
	path                "/tmp/mpd.fifo"
	format              "44100:16:2"
}

